name: run-tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9" # for antares-client's confluent-kafka dependency
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
        python -m pip install -I flake8
    - name: Style Checks
      run: flake8 tom_* --exclude=*/migrations/* --max-line-length=120

  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.8"] # TODO: add back 3.10, 3.11, 3.12
        # 3.12 not working for numpy
        # 3.10, 3.11 not working for antares-client's confluent-kafka dependency
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with test
          python -m pip install coveralls
          python -m pip install -I flake8
      - name: Run Tests
        run: |
          python -m pip freeze
          python manage.py test --exclude-tag=canary

  publish_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with test
          python -m pip install coverage coveralls
          python -m pip install -I flake8
      - name: Run Tests
        run: coverage run --include=tom_* manage.py test --exclude-tag=canary
      - name: Report Coverage
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
